# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go-licenses save . --save_path=licenses --force
builds:
  - env:
      # for go-sqlite3
      # - CGO_ENABLED=1
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}-
      {{- .Os }}
    format: zip
dockers:
  - image_templates:
      - ankane/pdscan:latest
      - ankane/pdscan:{{ .Tag }}
    build_flag_templates:
      - --platform=linux/amd64
    extra_files:
      - licenses
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
