name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    - uses: ankane/setup-mysql@v1
      with:
        database: pdscan_test
    - uses: ankane/setup-postgres@v1
      with:
        database: pdscan_test
    - run: make test
