name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
        cache: true
    - uses: ankane/setup-mysql@v1
      with:
        database: pdscan_test
    - uses: ankane/setup-postgres@v1
      with:
        database: pdscan_test
    - uses: ankane/setup-sqlserver@v1
      with:
        accept-eula: true
    - run: sqlcmd -U SA -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE pdscan_test'
    - uses: ankane/setup-mongodb@v1
    - run: make test
      env:
        SQLSERVER_URL: sqlserver://SA:YourStrong!Passw0rd@localhost:1433?database=pdscan_test
